background #141a19
foreground #00ba67
cursor #ac0303
cursor_text_color #000000
selection_background #2abd89
selection_foreground #0e130e
#: Black
color0 #30352e
color8 #5d675a
#: Red
color1 #ac0303
color9 #fb4444
#: Green
color2 #077506
color10 #00bb00
#: Yellow
color3 #b0a30e
color11 #def112
#: Blue
color4 #1763be
color12 #129ae7
#: Magenta
color5 #946c9e
color13 #dd73fb
#: Cyan
color6 #06989a
color14 #34e2e2
#: White
color7 #1f8f67
color15 #2abd89
