# ~/.config/tmux/themes/mgk-tmux-theme.conf

####
# Theme
####
# Theme Settings
set -g @nova-nerdfonts true
set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #W"

# Theme Colors
set -g "@nova-pane-active-border-style" "#111111"
set -g "@nova-pane-border-style" "#111111"

# Color of the notification bar. (Defaults to yellow).
set -g message-style 'bg=#750000 fg=white bold'

# Change the Tmux Buffer Selection style from yellow to inverse.
set -g mode-style 'reverse'

# Status segment
set -g "@nova-status-style-bg" "#090909"
set -g "@nova-status-style-fg" "#666666"

set -g "@nova-status-style-active-bg" "#990000"
set -g "@nova-status-style-active-fg" "#bfbfbf"

set -g "@nova-status-style-double-bg" "#090909"

# Mode segment
set -g @nova-segment-mode "#{?client_prefix,X,O}"
set -g @nova-segment-mode-colors "#1c1c1c #bfbfbf"
#set -g @nova-segments-0-left "mode"

# Whoami segment
set -g @nova-segment-whoami "#(whoami)@#h"
set -g @nova-segment-whoami-colors "#1c1c1c #bfbfbf"
#set -g @nova-segments-0-right "whoami"

# Test
#set -g @nova-segment-test "#(echo "Hey.")"
#set -g @nova-segment-test-colors "#1c1c1c #bfbfbf"

# Gitmux
set -g @nova-segment-gitmux '#(gitmux "#{pane_current_path}")'
set -g @nova-segment-gitmux-colors "#1c1c1c #bfbfbf"

# Segment: CPU Usage. [ Bottom + Right ]
set -g @cpu_percentage_format "%5.1f%%"
set -g @nova-segment-cpu " #(~/.config/tmux/plugins/tmux-cpu/scripts/cpu_percentage.sh)"
set -g @nova-segment-cpu-colors "#1c1c1c #bfbfbf"

# Segment: Mem Usage. [ Bottom + Right ]
set -g @ram_percentage_format "%5.1f%%"
set -g @nova-segment-ram " #(~/.config/tmux/plugins/tmux-cpu/scripts/ram_percentage.sh)"
set -g @nova-segment-ram-colors "#1c1c1c #bfbfbf"

# Layout of Statusbar and widgets.
set -g @nova-rows 1
set -g @nova-segments-0-left "mode"
set -g @nova-segments-0-right "whoami"
set -g @nova-segments-1-left "cpu ram"
set -g @nova-segments-1-right "gitmux"

