set -g @plugin '/home/ld/.local/git/tmux-nova'

# Enable nerdfonts and such.
set -g @nova-nerdfonts true
#set -g @nova-nerdfonts-left 
#set -g @nova-nerdfonts-right 

# The layout of the statusbar. I think.
set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #W"

# This is the window tab color in the top row.
set -g @nova-status-style-active-bg "#990000"
set -g @nova-status-style-active-fg "#f8f8f2"

# Background color for most of the bottom row.
set -g @nova-status-style-double-bg "#1c1c1c"


# Segment: The TMUX mode indicator. [ Top + Left ]
set -g @nova-segment-mode "#{?client_prefix,卍,卐}"
set -g @nova-segment-mode-colors "#090909 #bfbfbf"

# Segment: The Whoami indicator. [ Top + Right ]
set -g @nova-segment-whoami "#(whoami)@#h"
set -g @nova-segment-whoami-colors "#090909 #bfbfbf"

# Segment: CPU Usage. [ Bottom + Right ]
set -g @cpu_percentage_format "%5.1f%%"
set -g @nova-segment-cpu " #(~/.config/tmux/plugins/tmux-cpu/scripts/cpu_percentage.sh)"
set -g @nova-segment-cpu-colors "#0d0d0d #f8f8f2"

# Segment: Mem Usage. [ Bottom + Right ]
set -g @ram_percentage_format "%5.1f%%"
set -g @nova-segment-ram " #(~/.config/tmux/plugins/tmux-cpu/scripts/ram_percentage.sh)"
set -g @nova-segment-ram-colors "#0d0d0d #f8f8f2"

# Layout of Statusbar and widgets.
set -g @nova-rows 1
set -g @nova-segments-0-left "mode"
set -g @nova-segments-0-right "whoami"
set -g @nova-segments-1-left ""
set -g @nova-segments-1-right "cpu ram"
