# Configuration file for mgk-bg

# Define the default theme
theme_config="sfw"

# Define themes
sfw_dirs=(
    "abstract"
    "abstract-subtle"
    "abstract-tilable"
    "america-maga"
    "america-misc"
    "america-trump"
    "anime-boys"
    "anime-general"
    "anime-girls"
    "anime-misc"
    "anubis"
    "apocalypse"
    "architecture-art"
    "architecture-old-world"
    "architecture-photos"
    "christian"
    "cyberpunk-art"
    "cyberpunk-battle"
    "cyberpunk-char"
    "cyberpunk-scene"
    "cyberpunk-urban"
    "cyberpunk-warrior"
    "fantasy-army"
    "fantasy-art"
    "fantasy-battle"
    "fantasy-char"
    "fantasy-creature"
    "fantasy-dragons"
    "fantasy-lotr"
    "fantasy-monster"
    "fantasy-necromancer"
    "fantasy-place"
    "fantasy-scene"
    "fantasy-undead"
    "fantasy-urban"
    "fantasy-warrior"
    "gaming-char"
    "gaming-misc"
    "girls-sfw"
    "historical-alt-timeline"
    "historical-misc"
    "ironpunk-airship"
    "ironpunk-battle"
    "ironpunk-urban"
    "ironpunk-vessel"
    "ironpunk-warrior"
    "japanese-art"
    "japanese-char"
    "japanese-warrior"
    "mapz-old-world"
    "mecha"
    "medieval-warrior"
    "military-airforce"
    "military-army"
    "military-army-legacy"
    "military-misc"
    "military-navy"
    "military-navy-legacy"
    "military-nukes"
    "misc-art"
    "misc-char"
    "misc-comic"
    "misc-cute"
    "misc-dark"
    "misc-digital"
    "misc-funny"
    "misc-girl-art"
    "misc-hacking"
    "misc-movie"
    "misc-mythology"
    "misc-piracy"
    "misc-place"
    "misc-scene"
    "misc-tallpapez"
    "misc-urban"
    "misc-warrior"
    "misc-widescreen"
    "nature-doggy"
    "nature-forest-art"
    "nature-forest-photos"
    "nature-kitty"
    "nature-misc-art"
    "nature-misc-photos"
    "nature-mountains-photos"
    "nature-oceanic-art"
    "nature-oceanic-photos"
    "powerfull"
    "README.md"
    "scifi-army"
    "scifi-art"
    "scifi-battle"
    "scifi-char"
    "scifi-place"
    "scifi-scene"
    "scifi-space-art"
    "scifi-starwars"
    "scifi-urban"
    "scifi-vessels"
    "scifi-w40k"
    "scifi-warrior"
    "steampunk-airship"
    "steampunk-army"
    "steampunk-battle"
    "steampunk-scene"
    "steampunk-urban"
    "steampunk-warrior"
    "unsorted"
)

nsfw_dirs=(
    "bloody"
    "creepy-art"
    "creepy-art-hrgiger"
    "creepy-forest"
    "creepy-misc"
    "creepy-monster"
    "creepy-place"
    "creepy-scene"
    "cyberpunk-char"
    "fantasy-necromancer"
    "furry"
    "furry-yiff"
    "horror-demon"
    "horror-eldritch"
    "horror-scene"
    "horror-thalasaphobia"
    "ironpunk-nazis"
    "japanese-monster"
    "misc-dank"
    "misc-dark"
    "monster-cosmic"
    "monster-giant"
    "monster-misc"
    "monster-ocean"
    "monster-zombies"
    "nsfw-unsorted"
    "scifi-warrior"
    "sexy-anime"
    "sexy-girls"
    "sexy-girls-anthro"
    "sexy-girls-realism"
    "sexy-photo-art"
    "sexy-time"
)

