#!/usr/bin/env bash
HOSTNAME=$(hostname)

xrdb -merge ~/.config/xorg/Xresources

~/.local/bin/xrandr-setup

# Execute commands based on the hostname
if [ "$HOSTNAME" = "orthanc" ]; then
    exec /usr/bin/awesome
elif [ "$HOSTNAME" = "barad-dur" ]; then
    exec /usr/bin/awesome
elif [ "$HOSTNAME" = "angband" ]; then
    exec /usr/bin/awesome
elif [ "$HOSTNAME" = "mairon" ]; then
    #exec /usr/bin/awesome
		exec /usr/bin/dbus-launch --exit-with-session /usr/local/bin/stumpwm
else
    #exec /usr/bin/awesome
		exec /usr/bin/dbus-launch --exit-with-session /usr/local/bin/stumpwm
fi
